### ISSUE TITLE
Ubuntu-Regular not using local font

### ISSUE THREAD

**Issue by caleb531** [google/fonts#1037]
Hi,

On my system (macOS Sierra), I have installed the Ubuntu font via `brew cask install font-ubuntu`. The "Regular" font family is listed on my system under the font name "Ubuntu". However, the generated CSS for Ubuntu expects the local name to be either "Ubuntu Regular" or "Ubuntu-Regular" (see here). Adding local('Ubuntu') to the list fixes the issue completely. Therefore, I simply propose updating your font CSS generator to handle this case.

Here's the URL I'm using:
https://fonts.googleapis.com/css?family=Ubuntu:400

And here's the relevant CSS for that resource:

```css
/* latin */
@font-face {
  font-family: 'Ubuntu';
  font-style: normal;
  font-weight: 400;
  src: local('Ubuntu Regular'), local('Ubuntu-Regular'), url(https://fonts.gstatic.com/s/ubuntu/v10/zvCUQcxqeoKhyOlbifSAaevvDin1pK8aKteLpeZ5c0A.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
}
```

Again, notice that `local('Ubuntu Regular')` and `local('Ubuntu-Regular')`, however only `local('Ubuntu')` is recognized. Other font weights like `Ubuntu-Light` work correctly; this only seems to affect the default font weight `400`, and probably applies to most other hosted fonts as well.

Thanks,
Caleb
