### ISSUE TITLE
Wrong font-weight loaded for Roboto Condensed 400

### ISSUE THREAD

**Issue by nikparo** [google/fonts#1046]
`<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400" rel="stylesheet">` loads the wrong font-weight. You get `700` instead of `400`.

Example:
[https://jsfiddle.net/nik10110/ea8z0b6n/](https://jsfiddle.net/nik10110/ea8z0b6n/)

``` html
<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i" rel="stylesheet">

<p class="light">The quick brown fox jumps over the lazy dog</p>
<p class="light italic">The quick brown fox jumps over the lazy dog</p>
<p class="normal">The quick brown fox jumps over the lazy dog</p>
<p class="normal italic">The quick brown fox jumps over the lazy dog</p>
<p class="bold">The quick brown fox jumps over the lazy dog</p>
<p class="bold italic">The quick brown fox jumps over the lazy dog</p>
```

``` css
body {
  font-family: 'Roboto Condensed', sans-serif;
  font-size: 40px;
}

.light {
  font-weight: 300;
}
.normal {
  font-weight: 400;
}
.bold {
  font-weight: 700;
}
.italic {
  font-style: italic;
}
```
