### ISSUE TITLE
font-display: not working in webpack production mode

### ISSUE THREAD

**Issue by romanmarkelov** [google/fonts#1883]
Webpack in production mode remove a last declaration in a ruleset and if font-display will be last that its fails

work
```css
@font-face {
  font-family: 'Roboto';
  src: url('../fonts/roboto/Roboto-Light.woff2') format('woff2'),
  url('../fonts/roboto/Roboto-Light.woff') format('woff');
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}
```
fail
```css
@font-face {
  ...
  font-display: swap 
}
```
