### ISSUE TITLE
Microfiche font

### ISSUE THREAD

**Issue by aubergine10** [google/fonts#1887]
Request: A font where all non-space characters are small identically-sized black rectangles.

At `font-size: 2px` each non-space character is be 2px high by 1px wide. No spacing between characters.  Space characters would be 2px x 2px.

Can't find anything like it on the internet. Maybe something google could create? Or the person who posted #1833 ? :)

### Use case 1: Document minimaps (like [atom minimap](https://atom.io/packages/minimap))

![minimap](https://user-images.githubusercontent.com/1386719/54572920-c9958780-49e1-11e9-9085-31dd65a5aff5.png)

### Use case 2: Media breakpoints

For example, to microfiche an article preview text on small screens:

```css
@media (min-width: 200px) {
    article .preview-text { font-family: 'microfiche', sans-serif; font-size: 2px; line-height: 1em; }
}
```
