### ISSUE TITLE
Google Fonts returning suboptimal fonts for Microsoft Edge Canary

### ISSUE THREAD

**Issue by iamakulov** [google/fonts#2030]
I just noticed that Google Fonts return suboptimal web fonts (as in, `ttf` instead of `woff2`) for Microsoft Edge Canary. This appears to be a user-agent issue.

## Steps to reproduce

1. Set your user agent to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3818.0 Safari/537.36 Edg/77.0.188.0`.

2. Open https://fonts.googleapis.com/css?family=Roboto

**Actual result:**

The URL returns the ttf version of the font:

```css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v19/KFOmCnqEu92Fr1Mu4mxP.ttf) format('truetype');
}
```

**Expected result:**

The URL returns the woff2 version of the font split by unicode ranges:

```css
/* cyrillic-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v19/KFOmCnqEu92Fr1Mu72xKOzY.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
/* cyrillic */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v19/KFOmCnqEu92Fr1Mu5mxKOzY.woff2) format('woff2');
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
...
```

## Screenshots of the repo

Original Microsoft Edge Canary user-agent:

![image](https://user-images.githubusercontent.com/2953267/59474557-042b8680-8e50-11e9-8f50-ceb358a068f1.png)

Chrome user-agent overwritten through DevTools:

![image](https://user-images.githubusercontent.com/2953267/59474565-0beb2b00-8e50-11e9-90d0-14a488c72b11.png)
