### ISSUE TITLE
Symbol glyphs not in any subset

### ISSUE THREAD

**Issue by edemaine** [google/fonts#2077]
I'm trying to get a monospace font that includes a glyph for ␣ (U+2423 Open Box).  When I input this as sample text in https://fonts.google.com/, I see that Inconsolata includes the glyph.  (Though, if I click on the sample text, it immediately turns into a box, suggesting something is up.)  But on Chrome, https://fonts.googleapis.com/css?family=Inconsolata&display=swap&subset=latin-ext,vietnamese generates the following CSS which doesn't include U+2423 in any `unicode-range`:

```css
/* vietnamese */
@font-face {
  font-family: 'Inconsolata';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Inconsolata Regular'), local('Inconsolata-Regular'), url(https://fonts.gstatic.com/s/inconsolata/v17/QldKNThLqRwH-OJ1UHjlKGlW5qhWxg.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+1EA0-1EF9, U+20AB;
}
/* latin-ext */
@font-face {
  font-family: 'Inconsolata';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Inconsolata Regular'), local('Inconsolata-Regular'), url(https://fonts.gstatic.com/s/inconsolata/v17/QldKNThLqRwH-OJ1UHjlKGlX5qhWxg.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Inconsolata';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Inconsolata Regular'), local('Inconsolata-Regular'), url(https://fonts.gstatic.com/s/inconsolata/v17/QldKNThLqRwH-OJ1UHjlKGlZ5qg.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

I believe the issue is that this glyph isn't in any subset.  The idea of a Symbols subset is mentioned in a few issues (#1350, #1346).  I'd also be happy with a mechanism (`subset=all` if you will) that omits the `unicode-range`... I'd like to avoid using the Font Loader, though I imagine that would also solve the problem.
