### ISSUE TITLE
Disable Latin subset

### ISSUE THREAD

**Issue by JodiWarren** [google/fonts#2230]
I understand that by providing `unicode-range`, it makes sure that the all the characters on a single page are served by the fonts, with smaller subsets just downloading the required chunks.

It's a really nice system, but I was wondering if there was a way of excluding a certain subset? In my use case, I'd like to exclude the Latin subset.

That would let me more elegantly fall back to another typeface without downloading them all, manually subsetting, and hosting them.

I'm imagining something that could be requested with an `exclude-subset` url param.

So you'd use something like: `"https://fonts.googleapis.com/css?family=Noto+Sans+SC:300,400,500&display=swap&subset=chinese-simplified&exclude-subset=latin"`

**Comment by JGJP** [comment]
I would also like to see a feature like this. This would allow latin characters to fallback to a font of my choosing.

**Comment by Kristinita** [comment]
+1 for a simple exclusion of any subset, not solely Latin.

### Example

For example, link to “Play” font:

```text
https://fonts.googleapis.com/css?family=Play:700&display=swap
```

When we click on the link, we see, in particular, this:

```css
/* greek */
@font-face {
  font-family: 'Play';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/play/v17/6ae84K2oVqwItm4TCpMy2knT.woff2) format('woff2');
  unicode-range: U+0370-03FF;
}
/* vietnamese */
@font-face {
  font-family: 'Play';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/play/v17/6ae84K2oVqwItm4TCp8y2knT.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB;
}
```

I’m sure I won’t be using Greek and Vietnamese characters, and I wish there was an option to disable `greek` and `vietnamese` subsets.

Thanks.
