### ISSUE TITLE
Inter fonts lacks italics

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#2386]

**Comment by virgofx** [comment]
Version 3.12 includes the italic variable font. @m4rc1e Anyway to get this included?

**Comment by adamgreenough** [comment]
Absolutely love this font, really struggling without italics. Let's please get this in if possible! 😄

**Comment by bartek-szymanski** [comment]
Is there any time schedule when will Inter font be updated to include italic?

**Comment by davelab6** [comment]
https://github.com/google/fonts/issues/2576 explains a bit more why this is the case. 

https://github.com/rsms/inter/blob/5ea76aef5a6790085ef2427a726d9953772a26ef/Makefile#L55-L56 suggests there is now a separate italic file that we can use.

**Comment by virgofx** [comment]
To clarify ... I don't have an issue with a separate font file for Italic (or one). Just curious when it'll be available on Google CDN?

**Comment by mahnunchik** [comment]
@rsms Do you know why italic is missing from Google Fonts?

**Comment by brycewray** [comment]
Unless/until Google Fonts makes an italic version available, one can do the following:

1. Download the full variable-font version of Inter (https://github.com/rsms/inter/releases/ should always have the latest).
2. Subset it so it's not enormously large (see https://michaeljherold.com/2015/05/04/creating-a-subset-font/ for an explanation of using the Python `fonttools` library for this purpose). 

I am currently doing this on my own site with a single Inter v.3.15 variable-font file that ends up at a little under 41K after subsetting, using the following CSS:

```css
/* === entire 'fonts.css' file === */
/* === Inter, variable === */
/* === (see https://thetrevorharmon.com/blog/how-to-prepare-and-use-variable-fonts-on-the-web) === */
/* latin */
@font-face {
  font-family: 'Inter';
  font-weight: 1 999;
  font-style: oblique 0deg 10deg;
  font-display: swap;
  src: url('../fonts/Inter-3-15_subset_2020-08-20.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
/* latin */
@font-face {
  font-family: 'Inter';
  font-weight: 1 999;
  font-style: normal;
  font-display: swap;
  src: url('../fonts/Inter-3-15_subset_2020-08-20.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

/* === within 'index.css' (which imports 'fonts.css' and some other .css files) === */

i, cite, em, var, address, dfn, .italic {
  font-variation-settings: 'slnt' -7;
  font-style: oblique 7deg;
}

/* === The 7-degree thing is up to you. Some suggest 10 degrees, but that looks **too** slanted to me. === */

```

This works for my site, anyway. Safari in particular has some tendency to over-slant when headline-level text is bolded, such as for `h2` and the like, but this otherwise seems to do well.

**Comment by yetisyny** [comment]
> #2576 explains a bit more why this is the case.
>
> https://github.com/rsms/inter/blob/5ea76aef5a6790085ef2427a726d9953772a26ef/Makefile#L55-L56 suggests there is now a separate italic file that we can use.

So, could you use that italics file then, to make the italics variant available in Google Fonts? It already exists, after all. You could just make it available the same way italics is available in other Google Fonts.

Many other variable fonts already have italics variants available on Google Fonts, i.e. Raleway, Roboto Mono, Rubik, Bitter, Exo 2, Merriweather Sans, EB Garamond, Vollkorn, and Literata. I don’t see what is blocking Google Fonts from just using the existing italics file for the Inter font, seems like an easy fix.

I looked at the Inter fonts GitHub and it says that if there are any Google Fonts issues with it to report them here instead of at that GitHub.

So, if there is some kind of issue with how Inter codes for italics, as you suggest in #2576, perhaps just go ahead and change it to do it in a way compatible with current web browsers and the &lt;i&gt; tag or CSS “font-style: italic;” that is typically used for italics, and then hopefully it is possible to just directly upload the fixed version to Google Fonts, or (alternatively) submit it as a pull request to the Inter font with the fixes and then upload the fixed version to Google Fonts.

And if the issue is not on Google’s end but on Inter’s end... well, the Inter GitHub said that this is where to report issues with it that occur in Google Fonts, but, please feel free to tell them anything that needs changing over at https://github.com/rsms/inter/, if there is actually an issue on their end rather than on Google’s end.

I am looking to use the Inter font, including italics, on a MediaWiki wiki where Google Fonts do work but where @brycewray’s [creative workaround](#issuecomment-691503098) is not technically possible (specifically, there is no way to upload font files to the web server since only certain file types can be hosted; the fonts have to be remotely hosted by Google Fonts for it to work due to technical limitations). Thanks.

**Comment by brycewray** [comment]
I should note also that I have since found additional issues with the CSS I put above in terms of getting different browsers to “behave” so, as of now, here are the relevant sections of my site’s SCSS:

```scss
/* === entire `_fonts.scss`=== */
/* === Inter, variable === */
/* === 
references:
https://thetrevorharmon.com/blog/how-to-prepare-and-use-variable-fonts-on-the-web
https://rwt.io/typography-tips/getting-bent-current-state-italics-variable-font-support
=== */
/* latin */
@font-face {
  font-family: 'Inter';
  font-weight: 1 999;
  font-style: normal;
  font-display: swap;
  src: url('../fonts/Inter-3-15_subset_2020-08-20.woff2') format('woff2-variations');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

```scss
/* === part of `_base.scss` === */

i, cite, em, var, address, dfn, h3, h5, h6 {  /* dealing with Inter VF */
  font-variation-settings: 'slnt' -7;
  /* previous is needed by Chromium and Safari; its presence makes Firefox "over-slant" Inter VF, 
     so we override that below with the @-moz-document url-prefix media query for Firefox */
  font-style: oblique 7deg;
  /* previous is needed by Firefox and Safari to prevent "over-slanting"; 
     it apparently has no effect on Chromium */
  @-moz-document url-prefix() {
    font-variation-settings: normal;
  }
}
```
