### ISSUE TITLE
Why do Roboto latin-ext character render small when unicode-range is used?

### ISSUE THREAD

**Issue by JosefJezek** [google/fonts#282]
Roboto font with unicode-range have bad latin-ext chars...

https://fonts.googleapis.com/css?family=Roboto:400&subset=latin-ext
### Chrome Version 51.0.2704.84 (64-bit) show smaller char `Ř` and other latin-ext chars

![image](https://cloud.githubusercontent.com/assets/2110319/16361922/ae789666-3b9f-11e6-9579-f660c69259a4.png)

``` css
/* latin-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v15/Fcx7Wwv8OzT71A3E1XOAjvesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v15/CWB0XYA8bzo0kSThX0UTuA.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
```
### `@font-face` without `unicode-range` is OK with this woff2 font

``` css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v15/fIKu7GwZTy_12XzG_jt8eA.woff2) format('woff2');
}
```

![image](https://cloud.githubusercontent.com/assets/2110319/16362102/a6802450-3ba5-11e6-9e49-a8806d5fe38d.png)
