### ISSUE TITLE
Raleway font rendering issue on ios 14

### ISSUE THREAD

**Issue by ruslandoga** [google/fonts#2900]
👋

I have a problem with font returned for

```css
@font-face {
  font-family: "Raleway";
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/raleway/v18/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVvoorCMPrEVJz9d-c8.woff2)
    format("woff2");
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
```

<img width="1271" alt="Screenshot 2020-12-15 at 12 42 14" src="https://user-images.githubusercontent.com/67764432/102198155-19fd8a00-3ed3-11eb-804b-c24f4dc59772.png">

as it doesn't look quite the same as [on the google fonts preview](https://fonts.google.com/specimen/Raleway?preview.text=кто%20ценит%20своё%20время&preview.text_type=custom&subset=cyrillic&query=raleway&selection.family=Raleway:wght@500).

The problem persists on real devices as well. It doesn't seem to affect ios < 14.
