### ISSUE TITLE
CSS API Breaking Changes

### ISSUE THREAD

**Issue by DecliningLotus** [google/fonts#3870]
Hiya, 

A recent update to the CSS API essentially broke a portion of the [Fontsource](https://github.com/fontsource/fontsource) library with no option for me to actually fix the bug since the data previously used is no longer served by the platform.

Fontsource uses BOTH the CSS APIv1 and CSS APIv2 to gather all the files and information it needs since both APIs serve different files and formats which therefore can be offered as additional flexibility to developers downstream.

It seems that the CSS APIv1 was changed to serve files with the `unicode-range` CSS selector in the recent Noto update, a feature previously unique to CSS APIv2.

Before:
```css
...
/* japanese */
@font-face {
  font-family: 'Noto Sans JP';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/notosansjp/v28/-F62fjtqLzI2JPCgQBnw7HFYyQgP.woff2) format('woff2');
}
...
```

[After](https://fonts.googleapis.com/css?family=Noto+Sans+JP) (mirrors CSS APIv2):
```css
...
/* [2] */
@font-face {
  font-family: 'Noto Sans JP';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/notosansjp/v36/-F62fjtqLzI2JPCgQBnw7HFow2oe2EcP5pp0erwTqsSWs9Jezazjcb4.2.woff2) format('woff2');
  unicode-range: U+ffd7, U+ffda-ffdc, U+ffe0-ffe2, U+ffe4, U+ffe6, U+ffe8-ffee, U+1f100-1f10c, U+1f110-1f16c, U+1f170-1f1ac, U+1f200-1f202, U+1f210-1f234;
}
...
```

At least, my expectation would be that CSS APIv1 should be untouched while CSS APIv2 would be getting new updates? I would assume that's why we have two API versions in the first place. Would the team at Google be open to considering reverting the changes made to the CSS APIv1 or perhaps offer any other alternative solutions that we could collaborate on with?

References: fontsource/fontsource#353
