### ISSUE TITLE
Open Sans, letter 'J' gets clipped

### ISSUE THREAD

**Issue by SirRedrick** [google/fonts#4266]
**Description**
When using the font on the web, if overflow is set to hidden, some letters get clipped at the edge, the ones that I've noticed are italic 'y', 'p' 'A', 'J', 'j' 'x', and normal 'J' and 'j'

**To Reproduce**
You can see it on [Google Fonts](https://fonts.google.com/specimen/Open+Sans?preview.text=JJ&preview.text_type=custom) or if you use this font on the web page with the following styles on the element it's inside:
```css
.font {
	font-family: "Open Sans";
	font-size: 3rem;
	margin: 0 0.25rem;
	overflow: hidden;
}
```
[Codepen example](https://codepen.io/basheps/pen/dvXaPe)

**Expected behavior**
Expected all letters to be fully visible inside their container.

**Screenshots**
![Screenshot 2022-02-03 at 11 06 26](https://user-images.githubusercontent.com/53220479/152312720-587fd0e1-7294-4ea4-90f4-d5addbd8cd16.png)
