### ISSUE TITLE
Vazirmatn Kerning and hinting issue in Firefox

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#4463]
> Thanks for publishing Vazirmatn but there are two problems: Kerning and hinting.
I don't see any issue in the file uploaded by @yanone but as you can see in the picture all the kerning values has been set to zero during the font generation by fonts.google.com (why?!). I have used the fontmake tool from Google for generating all weights with no problem In the main repository of Vazirmatn. The very odd point is that when you check the preview in fonts.google.com with Google Chrome browser, kerning values are correct because it seems that the files are different when you see them in Firefox or when you download the family separately. Looks like that the fonts.google.com serves different files for each browser. Anyway kernings are lost by fonts.google.com!

![googlefonts-vazirmatn-kerning-issue](https://user-images.githubusercontent.com/3116038/161171329-bed63aa0-a2b6-42da-960d-4fab2aea947b.png)

![googlefonts-vazirmatn-kerning-issue2](https://user-images.githubusercontent.com/3116038/161169231-71ca2b9d-3d7e-40be-87ce-51dba0d05aad.png)

> The second problem is about hinting. I used ttfautohint for hinting and everything looked fine in the main repository but as you can see in the picture hinting has been destroyed by fonts.google.com!

![googlefonts-vazirmatn-hinting-issue](https://user-images.githubusercontent.com/3116038/161169433-b2fc8e5f-e45b-4e05-a935-18f0f70ad6c1.png)

> You can compare files by adding them on this page:
> https://rastikerdar.github.io/vazirmatn/en/lab

> Pictures are in Windows 10

_Originally posted by @rastikerdar in https://github.com/google/fonts/issues/4352#issuecomment-1085270998_

**Comment by rastikerdar** [comment]
Not only in Firefox but also after downloading (no matter which browser) the kerning positioning values are zero.

**Comment by rastikerdar** [comment]
Sorry the hinting problem is my mistake and should be fixed in the font itself (it's a bug in the main variable file) I will request for an update soon as I fixed the issue. However I think the kerning problem is on the fonts.google.com side and needs to be fixed by your engineers.

**Comment by rastikerdar** [comment]
I would like to request an update for Vazirmatn (to the newest version) due to "hinting" problem that has caused many rendering issues. I had to remove the hinting completely. Is it possible for you to fix the kerning issue and upgrading the font to the newest version at the same time please?
https://github.com/rastikerdar/vazirmatn/tree/master/fonts/variable

Essential changes since v32.1:

- Removed hinting totally
- Added missing glyphs (ZWJ, ZWNJ) - necessary for Arabic/Persian

Some issues caused by ttfautohint:
![Screenshot at 2022-04-02 14-23-23](https://user-images.githubusercontent.com/3116038/161377843-aad4a934-2b2c-4903-944d-cdfc96428508.png)

Thanks for your attention

**Comment by yanone** [comment]
I pushed the 32.102 update that fixes the hinting. Once it's merged, we need to make sure to keep this issue open to keep talking about the missing kerning.

@davelab6 What's the correct way forward to address the kerning issue in the API? Please advise.

**Comment by davelab6** [comment]
I've ask them to take a look.

**Comment by garretrieger** [comment]
This appears to be a problem that's happening when the fully variable font is being instanced to a specific point in the axis space. I'll investigate further.

**Comment by garretrieger** [comment]
Ok tracked this down to a bug in fonttools, which was recently fixed :) https://github.com/fonttools/fonttools/commit/47457b14d638ea133a85a11646e2b2d9bb5e4f0f

On our side we'll just need to repush Vazirmatn to build it with the updated version of fonttools that contains the fix. I'll try to get that done in the next few days.

**Comment by garretrieger** [comment]
FYI to follow up, the font fix and the fonttools fix have both been pushed out to version of Vazirmatn on the fonts api.

**Comment by rastikerdar** [comment]
Thank you @garretrieger, the problems are gone but there is an issue in api. The style set table "ss01" in Vazirmatn replaces Latin numbers with Persian ones. For example it replaces glyph "eight" with "uni06F8"

![ss01](https://user-images.githubusercontent.com/3116038/165622708-31e94624-ce6b-4154-9c86-e1beca4603d5.png)

This table exists without problems when you download the font family on fonts.google.com page, but the table doesn't exist when you request the font from api (https://fonts.googleapis.com/css2?family=Vazirmatn&display=swap). It seems slicing the font removes the "ss01" too:
```css
/* arabic */
@font-face {
  font-family: 'Vazirmatn';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/vazirmatn/v4/Dxx78j6PP2D_kU2muijPEe1n2vVbfJRklWgzCRWT7lDF.woff2) format('woff2');
  unicode-range: U+0600-06FF, U+200C-200E, U+2010-2011, U+204F, U+2E41, U+FB50-FDFF, U+FE80-FEFC;
}
/* latin-ext */
@font-face {
  font-family: 'Vazirmatn';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/vazirmatn/v4/Dxx78j6PP2D_kU2muijPEe1n2vVbfJRklWgzCR6T7lDF.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Vazirmatn';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/vazirmatn/v4/Dxx78j6PP2D_kU2muijPEe1n2vVbfJRklWgzCRCT7g.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

This is not a critical problem, but it's not bad to be aware of it and it would be great if this could be fixed.
Anyway, thank you very much for your efforts.
