### ISSUE TITLE
Font subsetting in the CSS API removes glyphs present in the full font

### ISSUE THREAD

**Issue by iamakulov** [google/fonts#7660]
**Describe the issue**
When fonts are being subset for [the CSS API](https://developers.google.com/fonts/docs/css2), they lose multiple glyphs, like e.g. `●←↑↓→`. The full fonts (available through [the Developer API](https://developers.google.com/fonts/docs/developer_api)) include these glyphs.

This leads to sites that use these glyphs looking off, especially if the designer has the full font installed locally and doesn’t notice missing glyphs because of that.

**To Reproduce**
Taking “Inter Tight” as an example:
- Go to https://codepen.io/iamakulov/pen/wvbawBY
- Uncomment the `@font-face` code. Observe the font that loads includes all glyphs:

   ![Screenshot 2024-05-13 at 20 48 16](https://github.com/google/fonts/assets/2953267/80c2dff7-c252-44b4-b456-39d042b7741e)

- Comment out the `@font-face` code back and uncomment the `@import` line. Observe the font that loads is missing the “●→” glyphs:

   ![Screenshot 2024-05-13 at 21 13 12](https://github.com/google/fonts/assets/2953267/e504d978-58dd-4501-8d66-a47ec9acb060)

“Inter Tight” is used an an example, but this affects all fonts I tested with. 

**Expected behavior**
The font loaded through the CSS API should include all glyphs present in the full font file.

**Comment by iamakulov** [comment]
One easy workaround Google Fonts can take is to include the full font as the very first `@font-face`:

```css
/* full font */
@font-face {
  font-family: 'Inter Tight';
  font-style: italic;
  font-weight: 100 900;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/intertight/v7/NGSnv5HMAFg6IuGlBNMjxJEL2VmU3NS7Z2mj6AiqWSRToK8EPg.woff2) format('woff2');
  /* Note: no unicode-range */
}
/* cyrillic-ext */
@font-face {
  font-family: 'Inter Tight';
  font-style: italic;
  font-weight: 100 900;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/intertight/v7/NGSyv5HMAFg6IuGlBNMjxLsCwadkREW-emmbxg.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
/* cyrillic */
@font-face {
  font-family: 'Inter Tight';
  font-style: italic;
  font-weight: 100 900;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/intertight/v7/NGSyv5HMAFg6IuGlBNMjxLsCwa5kREW-emmbxg.woff2) format('woff2');
  unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* ... */
```

Per the spec, [the later `@font-face`s take the precedence over the earlier ones](https://drafts.csswg.org/css-fonts/#ex-better-latin). So in this situation, the full font will only be downloaded if the page uses glyphs not present in the subsetted `@font-face`s.
